services:
  connect:
    container_name: connect
    image: quay.io/debezium/connect:latest
    ports:
     - 8083:8083
    links:
     - kafka:kafka
     - oracle:oracle
    volumes:
      - /tmp/debezium_files/ojdbc11.jar:/kafka/libs/ojdbc11.jar
      - /tmp/debezium_files/ojdbc8.jar:/kafka/libs/oracle-connector-java.jar
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=_connect_configs
     - OFFSET_STORAGE_TOPIC=_connect_offsets
     - STATUS_STORAGE_TOPIC=_source_connect_statuses
    depends_on:
      - kafka
      - oracle
