services:
  oracle:
    image: gvenzl/oracle-xe
    hostname: oracle
    container_name: oracle
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=badger
    volumes:
      - ${PWD}/scripts:/tmp/scripts
      - ${PWD}/scripts/setup_db.sh:/container-entrypoint-initdb.d/1_setup_db.sh

    healthcheck:
      test: ["CMD", "cat", "/tmp/setup_complete"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s 
